version: "3.8"
services:
  server:
    build: 
      args:
        - USER_ID=1000
        - GROUP_ID=1000
        - USERNAME=ahmed
      context: .
      dockerfile: Server.Dockerfile
    container_name: snapevent_server
    env_file:
      - ".env"
    environment:
      - CONFIG_PATH=/server/
    ports:
      - "50051:50051"
    depends_on:
      - db
    volumes:
      - ./:/server
    networks:
      - snapevent_network

  client:
    build: 
      args:
        - USER_ID=1000
        - GROUP_ID=1000
        - USERNAME=ahmed
      context: .
      dockerfile: Client.Dockerfile
    container_name: snapevent_client
    env_file:
      - ".env"
    environment:
      - CONFIG_PATH=/client/
    ports:
      - "9090:9090"
    volumes:
      - ./:/client
    networks:
      - snapevent_network
       
  db:
    build: 
      context: .
      dockerfile: postgres.Dockerfile
    ports:
      - "5432:5432"
    container_name: snapevent_db
    env_file:
      - ".env"
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
    volumes:
      - db_volume:/var/lib/postgresql/data
    networks:
      - snapevent_network
    
networks:
  snapevent_network:
    driver: bridge
volumes:
  db_volume:
    driver: local
    
 